# This workflow checks the links in plaintext and HTML files
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  #pull_request:
  # Schedule runs on 12:00 on day-of-month 1
  # see https://crontab.guru/
  # min hour day month day(week)
  schedule:
    - cron: '0 12 1 * *'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.1.0
      with:
        path: repository

    - name: Checkout the website
      uses: actions/checkout@v3.1.0
      with:
        ref: gh-pages
        path: website

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.8
      with:
        # 429: Too many requests
        args: >
          --accept 429
          --exclude "http://localhost:1313/"
          --verbose
          "repository/**/*.md"
          "website/**/*.html"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3.0.0
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
